[package]
name = "kappa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.30", features = ["derive"] }
ndarray = "0.16.1"
num-complex = "0.4.6"
statrs = "0.18.0"
