[package]
name = "kappa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
colored = "3.0.0"
ndarray = "0.16.1"
num-complex = "0.4.6"
statrs = "0.18.0"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", ".katex-header.html"]
