[book]
authors = ["kmaitreys"]
language = "en"
src = "src"
title = "Kappa: A Primer on Dust Opacities in the ISM"

[build]
build-dir = "../docs/book"

[output.html]
site-url = "/kappa/book"
theme = "theme"
additional-css = ["theme/book.css"]
fold = { enable = true, level = 5 }
git-repository-url = "https://github.com/ProsiaLAB/kappa"
git-repository-icon = "fa-github"
