name: Deploy Kappa Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOC_OUTPUT_DIR: target/doc # Where rustdoc generates its output
      MDBOOK_SOURCE_DIR: book       # Your mdBook source directory
      MDBOOK_OUTPUT_DIR: book/book  # Where mdBook builds its output (default is book/book)
      GITHUB_PAGES_OUTPUT_DIR: ./docs # This is now your source 'docs' folder!
      CRATE_NAME: kappa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # --- No need to create GITHUB_PAGES_OUTPUT_DIR explicitly, it's 'docs/'
      # --- No need to copy index.html or images, they are already in 'docs/'

      # --- Rustdoc Documentation (will go to prosialab.github.io/kappa/rustdoc/) ---
      - name: Generate Rustdoc
        run: cargo doc --no-deps

      - name: Prepare Rustdoc for deployment
        run: |
          # Create the specific subdirectory for rustdoc within the 'docs' folder
          mkdir -p ${{ env.GITHUB_PAGES_OUTPUT_DIR }}/rustdoc
          # Move the *contents* of your specific crate's documentation
          # directly into the 'rustdoc' subdirectory.
          mv ${{ env.RUSTDOC_OUTPUT_DIR }}/${{ env.CRATE_NAME }}/* ${{ env.GITHUB_PAGES_OUTPUT_DIR }}/rustdoc/

      # --- mdBook Documentation (will go to prosialab.github.io/kappa/book/) ---
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        run: mdbook build ${{ env.MDBOOK_SOURCE_DIR }}

      - name: Copy mdBook to GitHub Pages output
        run: |
          # Create the specific subdirectory for mdbook within the 'docs' folder
          mkdir -p ${{ env.GITHUB_PAGES_OUTPUT_DIR }}/book
          mv ${{ env.MDBOOK_OUTPUT_DIR }}/* ${{ env.GITHUB_PAGES_OUTPUT_DIR }}/book/

      # --- Deploy to GitHub Pages ---
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.GITHUB_PAGES_OUTPUT_DIR }} # Upload the 'docs' folder itself

  deploy-pages:
    needs: build-and-deploy-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4