name: Deploy Rust Docs

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build docs
        run: cargo doc --no-deps

      - name: Prepare publish directory
        run: |
          mkdir -p publish/docs 
          cp -r target/doc/* publish/docs/ 
          cp static/index.html publish/ 
          touch publish/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
